{{- range .Values.externalSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreRef }}
    kind: SecretStore
  target:
    name: {{ .name }}
  dataFrom:
  - extract:
      key: {{ .dataFrom }}

{{- end }}