{{- if .Values.deployment_task }}
{{- if .Values.deployment_task.autoscaling.enable }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployment_task.name }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Values.deployment_task.name }}
  minReplicas: {{ .Values.deployment_task.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployment_task.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.deployment_task.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        targetAverageValue: {{ .Values.deployment_task.autoscaling.targetMemory }}
    {{- end }}
    {{- if .Values.deployment_task.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.deployment_task.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}